services:
  - type: web
    name: dlady-booking
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000